---
- name: set PROMPT_COMMAND for audit log
  lineinfile:
    dest: "{{ bashrc_path }}"
    regexp: '^export PROMPT_COMMAND'
    line: "export PROMPT_COMMAND='RETRN_VAL=$?;/usr/bin/logger -p authpriv.info \"SECURE $(whoami) [$$]: $(history 1 | sed \"s/^[ ]*[0-9]\\+[ ]*//\" )\"'"
  when: bashrc_path is defined and bashrc_path != '' and (not bashrc_path is none)
  no_log: false


- name: set root in /etc/aliases
  lineinfile:
    dest: '/etc/aliases'
    regexp: '^root:'
    line: "root:\t\t{{ rootalias }}"
  when: rootalias is defined and rootalias != '' and (not rootalias is none)
  no_log: false
  notify:
    - newaliases

- name: set cron for ntp update
  cron:
    name: "set ntp update"
    state: present
    user: 'root'
    minute: "{{ ntp_cron_min }}"
    hour: "{{ ntp_cron_hour }}"
    job: "/usr/sbin/ntpdate pool.ntp.org > /dev/null 2>&1"
  become: yes
  no_log: false
  when: ntp_cron_min is defined and ntp_cron_hour is defined and ntp_cron_min != '' and ntp_cron_hour != '' and (not ntp_cron_min is none) and (not ntp_cron_hour is none)

- name: remove cron for ntp update
  cron:
    name: "set ntp update"
    state: absent
    user: 'root'
    minute: "{{ ntp_cron_min | default(omit) }}"
    hour: "{{ ntp_cron_hour | default(omit) }}"
    job: "/usr/sbin/ntpdate pool.ntp.org > /dev/null 2>&1"
  become: yes
  no_log: false
  when: ntp_cron_min is undefined or ntp_cron_hour is undefined or ntp_cron_min == '' or ntp_cron_hour == '' or ntp_cron_min is none or ntp_cron_hour is none

